[package]
name = "polars-plan"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
description = "Lazy query engine for the Polars DataFrame library"

[lib]
doctest = false

[dependencies]
libloading = { workspace = true, optional = true }
polars-arrow = { workspace = true }
polars-buffer = { workspace = true }
polars-compute = { workspace = true }
polars-config = { workspace = true }
polars-core = { workspace = true, features = ["algorithm_group_by", "lazy", "zip_with", "random"] }
polars-defs = { workspace = true }
polars-descriptions = { workspace = true }
polars-error = { workspace = true }
polars-ffi = { workspace = true, optional = true }
polars-io = { workspace = true, features = ["lazy", "csv", "async"] }
polars-json = { workspace = true, optional = true }
polars-parquet = { workspace = true, optional = true }
polars-utils = { workspace = true }

bitflags = { workspace = true }
blake3 = { workspace = true }
bytemuck = { workspace = true }
bytes = { workspace = true, features = ["serde"] }
chrono = { workspace = true, optional = true }
chrono-tz = { workspace = true, optional = true }
digest-io = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
hashbrown = { workspace = true }
hex = { workspace = true }
indexmap = { workspace = true }
memmap = { workspace = true }
murmur3 = { workspace = true }
num-traits = { workspace = true }
percent-encoding = { workspace = true }
pyo3 = { workspace = true, optional = true }
rayon = { workspace = true }
recursive = { workspace = true }
regex = { workspace = true, optional = true }
schemars = { workspace = true, features = ["either1"], optional = true }
serde = { workspace = true, features = ["rc"], optional = true }
serde_json = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
slotmap = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3"

[build-dependencies]
hex = { workspace = true }
sha2 = { workspace = true }
version_check = { workspace = true }

[features]
# debugging utility
debugging = []
python = ["dep:pyo3", "polars-utils/python", "polars-ffi", "polars-core/object", "serde"]
serde = [
  "dep:serde",
  "dep:serde_json",
  "polars-buffer/serde",
  "polars-config/serde",
  "polars-core/serde-lazy",
  "polars-core/serde",
  "polars-defs/serde",
  "polars-io/serde",
  "polars-utils/serde",
  "polars-compute/serde",
  "either/serde",
  "slotmap/serde",
]
parquet = ["polars-io/parquet", "polars-parquet"]
cloud = ["polars-io/cloud"]
ipc = ["polars-io/ipc"]
json = ["polars-io/json", "polars-json"]
scan_lines = []
csv = ["polars-io/csv"]
temporal = [
  "chrono",
  "polars-core/temporal",
  "polars-defs/temporal",
  "polars-core/dtype-date",
  "polars-core/dtype-datetime",
  "polars-core/dtype-time",
  "polars-core/dtype-i8",
  "polars-core/dtype-i16",
]
# debugging purposes
fmt = ["polars-core/fmt"]
strings = ["polars-core/strings"]
future = []
dtype-u8 = ["polars-core/dtype-u8"]
dtype-u16 = ["polars-core/dtype-u16"]
dtype-u128 = ["polars-core/dtype-u128"]
dtype-i8 = ["polars-core/dtype-i8"]
dtype-i128 = ["polars-core/dtype-i128"]
dtype-i16 = ["polars-core/dtype-i16"]
dtype-f16 = ["polars-core/dtype-f16"]
dtype-decimal = ["polars-core/dtype-decimal", "dtype-i128"]
dtype-date = ["polars-defs/dtype-date", "temporal"]
dtype-datetime = ["polars-defs/dtype-datetime", "temporal"]
dtype-duration = [
  "polars-core/dtype-duration",
  "polars-defs/dtype-duration",
  "temporal",
]
dtype-time = ["polars-defs/dtype-time", "temporal"]
dtype-array = ["polars-core/dtype-array"]
dtype-categorical = ["polars-core/dtype-categorical"]
dtype-extension = ["polars-core/dtype-extension"]
dtype-map = ["polars-core/dtype-map"]
dtype-struct = ["polars-core/dtype-struct"]
object = ["polars-core/object"]
list_filter = []
list_gather = []
list_count = []
array_count = ["dtype-array"]
trigonometry = []
sign = []
timezones = ["chrono-tz", "polars-defs/timezones", "polars-core/timezones", "regex"]
binary_encoding = []
string_encoding = []
true_div = []
nightly = ["polars-utils/nightly"]
extract_jsonpath = []
dsl-schema = [
  "dep:schemars",
  "dep:sha2",
  "dep:serde_json",
  "serde_json/preserve_order",
  "serde",
  "polars-arrow/dsl-schema",
  "polars-buffer/schemars",
  "polars-core/dsl-schema",
  "polars-defs/dsl-schema",
  "polars-io/dsl-schema",
  "polars-utils/dsl-schema",
  "polars-compute/dsl-schema",
]

# operations
bitwise = ["polars-core/bitwise"]
approx_unique = ["polars-core/approx_unique"]
approx_quantile = ["polars-compute/approx_quantile"]
is_in = []
repeat_by = []
round_series = []
is_first_distinct = ["polars-core/is_first_distinct"]
is_last_distinct = ["polars-core/is_last_distinct"]
is_unique = []
is_between = []
is_close = []
cross_join = []
asof_join = ["polars-defs/asof_join"]
iejoin = ["polars-defs/iejoin"]
concat_str = []
business = []
range = ["dtype-array"]
mode = []
cum_agg = []
interpolate = []
interpolate_by = []
rolling_window = [
  "polars-core/rolling_window",
]
rolling_window_by = [
  "polars-core/rolling_window_by",
  "polars-defs/rolling_window_by",
]
rank = []
diff = []
pct_change = []
moment = []
abs = []
random = ["polars-core/random", "polars-defs/random"]
dynamic_group_by = ["polars-core/dynamic_group_by", "dtype-date", "dtype-datetime"]
ewma = []
ewma_by = []
dot_diagram = []
unique_counts = []
log = []
chunked_ids = []
list_to_struct = []
array_to_struct = []
row_hash = ["polars-core/row_hash"]
reinterpret = ["polars-core/reinterpret"]
string_pad = []
string_normalize = []
string_reverse = []
string_to_integer = []
arg_where = []
index_of = []
search_sorted = []
merge_sorted = []
meta = []
pivot = ["polars-core/rows"]
top_k = []
semi_anti_join = ["polars-defs/semi_anti_join"]
cse = []
propagate_nans = []
coalesce = []
fused = []
list_sets = []
list_drop_nulls = []
list_sample = []
cutqcut = []
rle = []
extract_groups = ["regex", "dtype-struct"]
ffi_plugin = ["libloading", "polars-ffi"]
dsl_rewrite = ["polars-ffi?/dsl_rewrite"]
hive_partitions = []
peaks = []
cov = []
hist = []
replace = []
find_many = []
month_start = []
month_end = []
offset_by = []
allow_unused = ["polars-io/allow_unused"]

bigidx = ["polars-core/bigidx", "polars-utils/bigidx", "dtype-i128"]
polars_cloud_client = ["serde"]
polars_cloud_server = ["serde"]
ir_serde = ["serde", "polars-utils/ir_serde"]

[package.metadata.docs.rs]
features = [
  "bitwise",
  "temporal",
  "serde",
  "rolling_window",
  "rolling_window_by",
  "timezones",
  "dtype-date",
  "extract_groups",
  "dtype-datetime",
  "asof_join",
  "dtype-duration",
  "is_first_distinct",
  "pivot",
  "dtype-array",
  "is_last_distinct",
  "dtype-time",
  "month_start",
  "month_end",
  "offset_by",
  "parquet",
  "strings",
  "row_hash",
  "json",
  "python",
  "cloud",
  "string_to_integer",
  "pct_change",
  "list_gather",
  "list_filter",
  "dtype-i16",
  "round_series",
  "cutqcut",
  "async",
  "ewma",
  "ewma_by",
  "random",
  "chunked_ids",
  "repeat_by",
  "is_in",
  "log",
  "string_reverse",
  "list_sets",
  "propagate_nans",
  "mode",
  "rank",
  "hist",
  "object",
  "approx_unique",
  "approx_quantile",
  "dtype-categorical",
  "merge_sorted",
  "bigidx",
  "cov",
  "list_sample",
  "dtype-i8",
  "fused",
  "binary_encoding",
  "list_drop_nulls",
  "fmt",
  "list_to_struct",
  "string_pad",
  "diff",
  "rle",
  "is_unique",
  "find_many",
  "string_encoding",
  "ipc",
  "index_of",
  "search_sorted",
  "unique_counts",
  "dtype-u8",
  "dtype-struct",
  "peaks",
  "abs",
  "interpolate",
  "interpolate_by",
  "list_count",
  "cum_agg",
  "top_k",
  "moment",
  "semi_anti_join",
  "replace",
  "dtype-u16",
  "dtype-f16",
  "regex",
  "dtype-decimal",
  "arg_where",
  "business",
  "range",
  "meta",
  "hive_partitions",
  "concat_str",
  "coalesce",
  "dot_diagram",
  "trigonometry",
  "true_div",
  "sign",
]
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true
