_extends: polars:release-drafter.yml

name-template: Rust Polars $RESOLVED_VERSION
tag-template: rs-$RESOLVED_VERSION
tag-prefix: rs-

include-labels:
  - rust

version-resolver:
  minor:
    labels:
      - breaking
      - breaking rust
  default: patch

categories:
  - title: 🏆 Highlights
    labels: highlight
  - title: 💥 Breaking changes
    labels:
      - breaking
      - breaking rust
  - title: 🚀 Performance improvements
    labels: performance
  - title: ✨ Enhancements
    labels: enhancement
  - title: 🐞 Bug fixes
    labels: fix
  - title: 📖 Documentation
    labels: documentation
  - title: 📦 Build system
    labels: build
  - title: 🛠️ Other improvements
    labels:
      - deprecation
      - internal
