[package]
name = "pyo3-polars-derive"
version = "0.22.0"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pola-rs/pyo3-polars"
description = "Deprecated compatibility re-export of the Polars expression-plugin macro"

[lib]
proc-macro = true

[dependencies]
polars-plugin-derive = { workspace = true }
proc-macro2 = "1.0"
quote = "1.0"
