FROM mcr.microsoft.com/devcontainers/rust:1

# the linker is part of the image above, see
https://github.com/microsoft/vscode-dev-containers/blob/c4c22252ef095a111618d535a2201d7140cd7ae0/containers/rust/.devcontainer/library-scripts/rust-debian.sh#L146C64-L146C64

