import json
import os
import sys
from pathlib import Path

def toml_str(value):
    # The escapes json.dumps emits (\", \\, \n, \uXXXX, ...) are all valid in a TOML
    # basic string as well.
    return json.dumps(str(value))


python_path = Path(sys.executable).absolute()
cargo_dir = Path(__file__).absolute().parent.parent / ".cargo"
config_toml = cargo_dir / "config.generated.toml"
pyo3_signature = f"cpython-{sys.version_info[0]}.{sys.version_info[1]}-64bit"

lines = [
    "# Auto-generated by tools/update-cargo-env.py, included from .cargo/config.toml.",
    "# Rewritten from scratch on every build, so any edits here will be lost.",
    "",
    "[env]",
    f"PYO3_ENVIRONMENT_SIGNATURE = {toml_str(pyo3_signature)}",
    f"PYO3_PYTHON = {toml_str(python_path)}",
]

if cflags := os.environ.get("CFLAGS"):
    lines.append(f"CFLAGS = {toml_str(cflags)}")

if rustflags := os.environ.get("RUSTFLAGS"):
    lines += ["", "[build]", f"rustflags = {toml_str(rustflags)}"]

# On linux, building with dev profile might fail at link time, because debug symbols
# exceed 4 GB, so keep the debug info in separate files there.
if sys.platform == "linux":
    for profile in ("dev", "debug-release"):
        lines += ["", f"[profile.{profile}]", 'split-debuginfo = "unpacked"']

config_toml.write_text("\n".join(lines) + "\n")
